title:            elf11
description:      "Programming, data analysis, machine learning."
disqus_shortname: elf11
# Your site's domain goes here. When working locally use localhost server leave blank
# PS. If you set this wrong stylesheets and scripts won't load and most links will break.
# PPS. If you leave it blank for local testing home links won't work, they'll be fine for live domains though.
url:              http://elf11.github.io

# Owner/author information
owner:
  name:           Oana Niculaescu
  avatar:         avatar.jpg
  bio:            "Masters Student at University Politehnica of Bucharest"
  email:          oana.niculaescu@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        littleelf11
  facebook:       
  github:         elf11
  stackexchange:  
  #linkedin:       36508398
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:    https://plus.google.com/u/0/+OanaNiculaescu
  # kaggle:         http://www.kaggle.com/users/41181/sedielem

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
#  - title: Research
#    url: /research
#  - title: Software
#    url: /software
#  - title: ResLab
#    url: http://reslab.elis.ugent.be
#    external: true
  - title: r/machinelearning
    url: http://www.reddit.com/r/machinelearning
    external: true
  - title: Deep Learning G+
    url: https://plus.google.com/communities/112866381580457264725
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe
future:      true
pygments:    true
markdown:    kramdown

# Amount of posts to show on home page
paginate: 10
